### ISSUE TITLE
passenger count can revert to -1 on cancellation

### ISSUE THREAD

**Issue by sherifnada** [TPeterW/MiddRides-Android#27]

**Comment by sherifnada** [comment]
This is a shared responsibility between Android and Parse i.e: The Android client currently decrements 1 from the DB. This should not be the case; the backend should handle decrementing and incrementing counts.

**Immediate patch:** on Android, check if count == 0. If it does, do nothing. Otherwise, decrement 1 and put that in the DB.

**Proper fix:** From Android, call an API method on the backend that cancels the request. The backend should take care of decrementing any counts. Same thing for making a request as well.

**Comment by TPeterW** [comment]
The increment is a backend API method, it's just that the method doesn't have a positive integer check. The only way we can do this is to get the data from backend, see if it's 0 (which doesn't make too much sense because this means someone will have to pay for mistakes made by other people's phones), and decide whether to increment by -1 or not.

**Comment by TPeterW** [comment]
okay
